version: '3'
services:
  postgres:
    image: postgres:15
    hostname: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
