version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      FLASK_ENV: production
      FLASK_DEBUG: False
    depends_on:
      - postgres
